//export const server_url = "https://enatega.ninjascode.com/"
export const server_url = "https://www.dostava.com.au/"
//export const server_url = "http://192.168.1.102:8000/"
//export const cloudinary_upload_url = "https://api.cloudinary.com/v1_1/dgdpsy6t9/image/upload"
export const cloudinary_upload_url = "https://api.cloudinary.com/v1_1/dostava/image/upload"
export const cloudinary_category = "s84tnnnr"
export const cloudinary_food = "ra6jix5g"
export const cloudinary_profile = "nh9fd8i5"
